# IDS 570 – Text Extraction from Validated Dataset

This notebook:
1. Parses `Validated_dataset.docx` to extract categories, titles, source labels, descriptions, and URLs
2. Visits each URL (handles both PDFs and HTML pages, with a PubMed API shortcut)
3. Writes everything to a formatted Excel file

## Setup

In [1]:
# Run once to install dependencies
!pip install python-docx openpyxl requests beautifulsoup4 PyMuPDF lxml

Requirement already satisfied: python-docx in /Users/far/miniforge3/lib/python3.12/site-packages (1.2.0)
Requirement already satisfied: openpyxl in /Users/far/miniforge3/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: requests in /Users/far/miniforge3/lib/python3.12/site-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /Users/far/miniforge3/lib/python3.12/site-packages (4.13.5)
Requirement already satisfied: PyMuPDF in /Users/far/miniforge3/lib/python3.12/site-packages (1.27.2.2)
Requirement already satisfied: lxml in /Users/far/miniforge3/lib/python3.12/site-packages (6.0.3)
Requirement already satisfied: typing_extensions>=4.9.0 in /Users/far/miniforge3/lib/python3.12/site-packages (from python-docx) (4.15.0)
Requirement already satisfied: et-xmlfile in /Users/far/miniforge3/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/far/miniforge3/lib/python3.12/site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/far/miniforge3/lib/python3.12/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/far/miniforge3/lib/python3.12/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/far/miniforge3/lib/python3.12/site-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /Users/far/miniforge3/lib/python3.12/site-packages (from beautifulsoup4) (2.8)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import re
import time
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

import requests
from bs4 import BeautifulSoup
import fitz  # PyMuPDF
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
import pandas as pd

In [ ]:
# -- Configuration -------------------------------------------------
DATA_DIR = Path("../01_data")
INPUT_DOCX = DATA_DIR / "Validated_dataset.docx"
OUTPUT_XLSX = DATA_DIR / "equity_corpus_scraped.xlsx"
OUTPUT_CONTEXT_CSV = DATA_DIR / "equity_contexts.csv"
REQUEST_DELAY = 2  # seconds between requests
REQUEST_TIMEOUT = 60  # seconds before giving up
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}

## Step 1 – Parse the Word Document

We unzip the `.docx` and read the internal XML directly to reliably extract:
- Category headings
- Hyperlink URLs (from the relationships file)
- Link display text (title)
- Source labels (text after the em-dash)
- Description paragraphs (the line following each entry)

In [4]:
def parse_docx(path: str) -> list[dict]:
    """Extract entries from the docx by reading its internal XML."""
    W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
    R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    PKG = "http://schemas.openxmlformats.org/package/2006/relationships"

    with zipfile.ZipFile(path) as z:
        rels_xml = ET.fromstring(z.read("word/_rels/document.xml.rels"))
        doc_xml = ET.fromstring(z.read("word/document.xml"))

    # rId → URL lookup
    url_map = {}
    for rel in rels_xml.findall(f"{{{PKG}}}Relationship"):
        if "hyperlink" in rel.get("Type", ""):
            url_map[rel.get("Id")] = rel.get("Target")

    body = doc_xml.find(f"{{{W}}}body")
    records = []
    current_category = "Uncategorized"

    for para in body.findall(f".//{{{W}}}p"):
        texts = [t.text or "" for t in para.iter(f"{{{W}}}t")]
        full_text = "".join(texts).strip()
        if not full_text:
            continue

        # Detect heading style
        pPr = para.find(f"{{{W}}}pPr")
        style_val = ""
        if pPr is not None:
            pStyle = pPr.find(f"{{{W}}}pStyle")
            if pStyle is not None:
                style_val = pStyle.get(f"{{{W}}}val", "")

        if re.match(r"(?i)heading\s*[12]", style_val):
            current_category = full_text
            continue

        # Look for hyperlinks
        hyperlinks = para.findall(f"{{{W}}}hyperlink")
        if not hyperlinks:
            if records and records[-1]["description"] == "":
                if not re.match(r"\*?\*?\d+\.?\*?\*?\s", full_text):
                    records[-1]["description"] = full_text
            continue

        hl = hyperlinks[0]
        rId = hl.get(f"{{{R}}}id")
        if not rId or rId not in url_map:
            continue
        url = url_map[rId]

        hl_texts = [t.text or "" for t in hl.iter(f"{{{W}}}t")]
        link_text = "".join(hl_texts).strip()

        source_label = ""
        if "---" in full_text or "\u2014" in full_text:
            source_label = re.sub(r".*?(---|\u2014)\s*", "", full_text).strip()
            source_label = source_label.strip("*").strip()

        records.append(
            {
                "category": current_category,
                "title": link_text,
                "source_label": source_label,
                "url": url,
                "description": "",
            }
        )

    return records

In [5]:
records = parse_docx(INPUT_DOCX)
print(f"Total entries extracted: {len(records)}\n")

# Show category breakdown
cats = {}
for r in records:
    cats[r["category"]] = cats.get(r["category"], 0) + 1
for cat, count in cats.items():
    print(f"  • {cat}: {count}")

Total entries extracted: 221

  • Federal policy / government health policy documents: 32
  • Academic article abstracts: 100
  • State or local health department reports/documents: 29
  • NGO / nonprofit health reports/documents: 30
  • Structural / justice framing: 7
  • Distribution / access / resource framing: 8
  • Policy implementation / measurement / systems framing: 9
  • Mixed / ambiguous framing: 6

In [6]:
# Quick preview of the first few entries
df_preview = pd.DataFrame(records)
df_preview.head(10)

,category,title,source_label,url,description
0,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,Federal methods report on defining and measuri...
1,Federal policy / government health policy docu...,HHS Action Plan to Reduce Racial and Ethnic He...,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,Department-wide action plan framed around disp...
2,Federal policy / government health policy docu...,"Agency Program, Activity, and Policy Highlight...",ASPE / HHS,https://aspe.hhs.gov/sites/default/files/docum...,Cross-agency highlights document tying program...
3,Federal policy / government health policy docu...,Advancing Equity through Quantitative Analysis,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/docum...,Technical report on quantitative approaches fo...
4,Federal policy / government health policy docu...,2023 Capacity Assessment Update,HHS,https://aspe.hhs.gov/sites/default/files/docum...,Cross-agency capacity assessment that referenc...
5,Federal policy / government health policy docu...,Landscape of Area-Level Deprivation Measures a...,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/docum...,Federal report on indices and methods used to ...
6,Federal policy / government health policy docu...,Building Data Capacity for Patient-Centered Ou...,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/2021-...,Data-capacity report linking evidence infrastr...
7,Federal policy / government health policy docu...,Health Equity Guide,CDC,https://www.cdc.gov/health-communication/pdf/h...,Brief CDC guide defining health equity and com...
8,Federal policy / government health policy docu...,Focusing on Health Equity,CDC,https://stacks.cdc.gov/view/cdc/126226/cdc_126...,CDC overview document on the meaning and opera...
9,Federal policy / government health policy docu...,Promoting Health Equity: A Resource to Help Co...,CDC,https://stacks.cdc.gov/view/cdc/11130/cdc_1113...,Foundational CDC resource linking equity to SD...

## Step 2 – Scrape Text from Each URL

Three strategies:
- **PubMed links** → Use the NCBI E-utilities API (reliable, no JavaScript issues)
- **PDF links** → Download in memory and extract with PyMuPDF
- **HTML pages** → Parse with BeautifulSoup using targeted selectors

In [7]:
def extract_pmid(url: str) -> str | None:
    """Extract PubMed ID from a URL."""
    m = re.search(r"pubmed\.ncbi\.nlm\.nih\.gov/(\d+)", url)
    return m.group(1) if m else None


def scrape_pubmed_api(pmid: str) -> str:
    """Fetch abstract via NCBI E-utilities."""
    efetch_url = (
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
        f"?db=pubmed&id={pmid}&rettype=abstract&retmode=text"
    )
    try:
        resp = requests.get(efetch_url, timeout=30)
        resp.raise_for_status()
        return resp.text.strip()
    except Exception as e:
        return f"ERROR (PubMed API): {e}"


def scrape_url(url: str) -> str:
    """Download and extract text from a PDF or HTML page."""
    try:
        resp = requests.get(
            url, headers=HEADERS, timeout=REQUEST_TIMEOUT, allow_redirects=True
        )
        resp.raise_for_status()
        content_type = resp.headers.get("Content-Type", "")

        # ── PDF ──
        if "pdf" in content_type.lower() or url.lower().rstrip("/").endswith(".pdf"):
            doc = fitz.open(stream=resp.content, filetype="pdf")
            text = "\n".join(page.get_text() for page in doc)
            doc.close()
            return text.strip()

        # ── HTML ──
        soup = BeautifulSoup(resp.text, "lxml")
        for tag in soup(["script", "style", "nav", "footer", "header"]):
            tag.decompose()

        selectors = [
            "#abstract",
            ".abstract-content",
            "#enc-abstract",
            "div.abstract",
            "article",
            "main",
            '[role="main"]',
            "#content",
            ".content",
        ]
        for sel in selectors:
            node = soup.select_one(sel)
            if node and len(node.get_text(strip=True)) > 100:
                return node.get_text(separator="\n", strip=True)

        body = soup.find("body")
        if body:
            return body.get_text(separator="\n", strip=True)
        return soup.get_text(separator="\n", strip=True)

    except Exception as e:
        return f"ERROR: {e}"

In [8]:
# ── Scrape all URLs ──────────────────────────────────────
# This takes ~8-10 min for ~225 URLs with a 2s delay.

total = len(records)
print(f"Scraping {total} URLs (estimated {total * REQUEST_DELAY // 60} min)...\n")

for i, rec in enumerate(records, 1):
    url = rec["url"]
    short_url = url[:80] + ("..." if len(url) > 80 else "")

    pmid = extract_pmid(url)
    if pmid:
        rec["scraped_text"] = scrape_pubmed_api(pmid)
    else:
        rec["scraped_text"] = scrape_url(url)

    status = "✓" if not rec["scraped_text"].startswith("ERROR") else "✗"
    chars = len(rec["scraped_text"])
    print(f"[{i}/{total}] {status} {chars:>7,} chars │ {short_url}")

    time.sleep(REQUEST_DELAY)

n_ok = sum(1 for r in records if not r["scraped_text"].startswith("ERROR"))
n_fail = total - n_ok
print(f"\n{'='*50}")
print(f"Done! {n_ok} succeeded, {n_fail} failed")

Scraping 221 URLs (estimated 7 min)...

[1/221] ✓ 209,287 chars │ https://aspe.hhs.gov/sites/default/files/private/pdf/265566/developing-health-eq...
[2/221] ✓ 101,694 chars │ https://aspe.hhs.gov/sites/default/files/private/pdf/206166/DisparitiesActionPla...
[3/221] ✓ 187,896 chars │ https://aspe.hhs.gov/sites/default/files/documents/514310c76b9ed8afa49cd223002b4...
[4/221] ✓  36,744 chars │ https://aspe.hhs.gov/sites/default/files/documents/41fbd5e6cbc181b77f96076c3ec70...
[5/221] ✓  59,950 chars │ https://aspe.hhs.gov/sites/default/files/documents/fbbe2c601e231a8ce9089e4f02e27...
[6/221] ✓ 281,139 chars │ https://aspe.hhs.gov/sites/default/files/documents/8dc674c904723bf8a5ce4cfc8d3dc...
[7/221] ✓  98,871 chars │ https://aspe.hhs.gov/sites/default/files/2021-07/covid-pcor-report.pdf
[8/221] ✓  10,239 chars │ https://www.cdc.gov/health-communication/pdf/health-equity-guide-infographic-508...
[9/221] ✗     101 chars │ https://stacks.cdc.gov/view/cdc/126226/cdc_126226_DS1.pdf
[10/221] ✗      99 chars │ https://stacks.cdc.gov/view/cdc/11130/cdc_11130_DS1.pdf
[11/221] ✓   4,706 chars │ https://www.cdc.gov/healthcommunication/HealthEquityGuidingPrinciples.pdf
[12/221] ✓   3,843 chars │ https://www.cdc.gov/cancer/nbccedp/pdf/nbccedp-health-equity-strategies-508.pdf
[13/221] ✓  28,420 chars │ https://www.cdc.gov/health-equity-chronic-disease/media/pdfs/2024/04/GFF-eval-br...
[14/221] ✓  12,246 chars │ https://archive.cdc.gov/www_cdc_gov/coronavirus/2019-ncov/downloads/community/CD...
[15/221] ✓  99,965 chars │ https://www.cms.gov/files/document/cms-framework-health-equity.pdf
[16/221] ✓  62,986 chars │ https://www.cms.gov/files/document/2025-cms-omh-health-equity-data-book.pdf
[17/221] ✓  29,323 chars │ https://www.cms.gov/files/document/cms-2024-omh-data-definitions.pdf
[18/221] ✓ 144,481 chars │ https://www.cms.gov/files/document/path-forwardhe-data-paper.pdf
[19/221] ✓  57,545 chars │ https://www.cms.gov/priorities/innovation/data-and-reports/2023/assessing-equity...
[20/221] ✓   8,339 chars │ https://www.cms.gov/files/document/ahead-overview-fs.pdf
[21/221] ✗     130 chars │ https://www.hrsa.gov/sites/default/files/hrsa/about/news/hrsa-health-equity-repo...
[22/221] ✓ 107,683 chars │ https://www.cms.gov/files/document/paving-way-equity-cms-omh-progress-report.pdf
[23/221] ✓ 114,870 chars │ https://odphp.health.gov/sites/default/files/2022-04/HP2030-HealthEquityEnvironm...
[24/221] ✓  15,343 chars │ https://odphp.health.gov/sites/default/files/2021-11/Combined-508.pdf
[25/221] ✓  60,023 chars │ https://odphp.health.gov/sites/default/files/2021-09/Report%208_Implementation%2...
[26/221] ✓  50,775 chars │ https://www.cms.gov/files/document/cms-geographic-framework.pdf
[27/221] ✓ 124,545 chars │ https://www.cms.gov/files/document/fy-2023-advancing-rural-health-508.pdf
[28/221] ✓   2,919 chars │ https://thinkculturalhealth.hhs.gov/clas/standards
[29/221] ✓       0 chars │ https://www.ahrq.gov/research/findings/nhqrdr/index.html?utm_source=chatgpt.com
[30/221] ✗      76 chars │ https://health.gov/healthypeople
[31/221] ✗      91 chars │ https://www.samhsa.gov/behavioral-health-equity
[32/221] ✓   3,978 chars │ https://www.ihs.gov/newsroom/factsheets/disparities/
[33/221] ✓   2,060 chars │ https://pubmed.ncbi.nlm.nih.gov/16533114/
[34/221] ✓   1,533 chars │ https://pubmed.ncbi.nlm.nih.gov/21551385/
[35/221] ✓   1,438 chars │ https://pubmed.ncbi.nlm.nih.gov/21219164/
[36/221] ✓   1,109 chars │ https://pubmed.ncbi.nlm.nih.gov/26079819/
[37/221] ✓   1,787 chars │ https://pubmed.ncbi.nlm.nih.gov/26599030/
[38/221] ✓   1,404 chars │ https://pubmed.ncbi.nlm.nih.gov/26599023/
[39/221] ✓   2,810 chars │ https://pubmed.ncbi.nlm.nih.gov/27503965/
[40/221] ✓     961 chars │ https://pubmed.ncbi.nlm.nih.gov/30426876/
[41/221] ✓   2,834 chars │ https://pubmed.ncbi.nlm.nih.gov/31136507/
[42/221] ✓   1,397 chars │ https://pubmed.ncbi.nlm.nih.gov/31308599/
[43/221] ✓   1,323 chars │ https://pubmed.ncbi.nlm.nih.gov/31308603/
[44/221] ✓   1,287 chars │ https://pubmed.ncbi.nlm.nih.gov/31900101/
[45/221] ✓   1,700 chars │ https://pubmed.ncbi.nlm.nih.gov/32589207/
[46/221] ✓   1,065 chars │ https://pubmed.ncbi.nlm.nih.gov/33795992/
[47/221] ✓   1,729 chars │ https://pubmed.ncbi.nlm.nih.gov/33765139/
[48/221] ✓   3,027 chars │ https://pubmed.ncbi.nlm.nih.gov/35867507/
[49/221] ✗     103 chars │ https://onlinelibrary.wiley.com/doi/10.1111/1475-6773.14069
[50/221] ✓   2,633 chars │ https://pubmed.ncbi.nlm.nih.gov/36216706/
[51/221] ✓   4,427 chars │ https://pubmed.ncbi.nlm.nih.gov/36969681/
[52/221] ✓   3,128 chars │ https://pubmed.ncbi.nlm.nih.gov/37290132/
[53/221] ✓   4,258 chars │ https://pubmed.ncbi.nlm.nih.gov/37483653/
[54/221] ✓   2,027 chars │ https://pubmed.ncbi.nlm.nih.gov/37589700/
[55/221] ✓   2,459 chars │ https://pubmed.ncbi.nlm.nih.gov/37683597/
[56/221] ✓   1,806 chars │ https://pubmed.ncbi.nlm.nih.gov/37782727/
[57/221] ✓   3,771 chars │ https://pubmed.ncbi.nlm.nih.gov/37788031/
[58/221] ✓   1,448 chars │ https://pubmed.ncbi.nlm.nih.gov/37866830/
[59/221] ✓   1,581 chars │ https://pubmed.ncbi.nlm.nih.gov/37963360/
[60/221] ✓   1,546 chars │ https://pubmed.ncbi.nlm.nih.gov/37995262/
[61/221] ✓   3,682 chars │ https://pubmed.ncbi.nlm.nih.gov/38015863/
[62/221] ✓   1,266 chars │ https://pubmed.ncbi.nlm.nih.gov/39135594/
[63/221] ✓   2,515 chars │ https://pubmed.ncbi.nlm.nih.gov/38574270/
[64/221] ✓   2,731 chars │ https://pubmed.ncbi.nlm.nih.gov/38649983/
[65/221] ✓   4,674 chars │ https://pubmed.ncbi.nlm.nih.gov/38632975/
[66/221] ✓   2,976 chars │ https://pubmed.ncbi.nlm.nih.gov/38830006/
[67/221] ✓   2,853 chars │ https://pubmed.ncbi.nlm.nih.gov/24641879/
[68/221] ✓   2,952 chars │ https://pubmed.ncbi.nlm.nih.gov/39935016/
[69/221] ✓   1,840 chars │ https://pubmed.ncbi.nlm.nih.gov/39920763/
[70/221] ✓   2,563 chars │ https://pubmed.ncbi.nlm.nih.gov/39602551/
[71/221] ✓   3,661 chars │ https://pubmed.ncbi.nlm.nih.gov/36125468/
[72/221] ✓   2,817 chars │ https://pubmed.ncbi.nlm.nih.gov/36920932/
[73/221] ✓   4,187 chars │ https://pubmed.ncbi.nlm.nih.gov/38432524/
[74/221] ✓   3,550 chars │ https://pubmed.ncbi.nlm.nih.gov/30782161/
[75/221] ✓   2,291 chars │ https://pubmed.ncbi.nlm.nih.gov/32814445/
[76/221] ✓   1,410 chars │ https://pubmed.ncbi.nlm.nih.gov/36533458/
[77/221] ✓   2,341 chars │ https://pubmed.ncbi.nlm.nih.gov/38109515/
[78/221] ✓   2,985 chars │ https://pubmed.ncbi.nlm.nih.gov/29894902/
[79/221] ✓   4,303 chars │ https://pubmed.ncbi.nlm.nih.gov/40069696/
[80/221] ✗     105 chars │ https://academic.oup.com/phe/article-abstract/8/2/173/2362531
[81/221] ✗     106 chars │ https://academic.oup.com/phe/article-abstract/13/3/247/5874652
[82/221] ✗     109 chars │ https://academic.oup.com/heapol/article-abstract/30/8/1078/555203
[83/221] ✓  42,162 chars │ https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-025-21526-9
[84/221] ✓  67,121 chars │ https://bmchealthservres.biomedcentral.com/articles/10.1186/s12913-018-3501-3
[85/221] ✓  35,125 chars │ https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-8324-6
[86/221] ✓  65,664 chars │ https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-021-11594-y
[87/221] ✗     112 chars │ https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2815866
[88/221] ✗     116 chars │ https://jamanetwork.com/journals/jamapediatrics/article-abstract/2819321
[89/221] ✗     106 chars │ https://jamanetwork.com/journals/jama/article-abstract/2804847
[90/221] ✓       0 chars │ https://www.milbank.org/quarterly/articles/advocacy-for-health-equity-a-synthesi...
[91/221] ✗      89 chars │ https://bmjopen.bmj.com/content/10/11/e040180
[92/221] ✓   1,387 chars │ https://pubmed.ncbi.nlm.nih.gov/15781105/
[93/221] ✓   1,800 chars │ https://pubmed.ncbi.nlm.nih.gov/25032386/
[94/221] ✓   2,024 chars │ https://pubmed.ncbi.nlm.nih.gov/24354818/
[95/221] ✓   2,249 chars │ https://pubmed.ncbi.nlm.nih.gov/28402827/
[96/221] ✓     659 chars │ https://pubmed.ncbi.nlm.nih.gov/33326721/
[97/221] ✓   2,260 chars │ https://pubmed.ncbi.nlm.nih.gov/30212863/
[98/221] ✓   2,461 chars │ https://pubmed.ncbi.nlm.nih.gov/31714069/
[99/221] ✓   1,901 chars │ https://pubmed.ncbi.nlm.nih.gov/30480152/
[100/221] ✓     398 chars │ https://pubmed.ncbi.nlm.nih.gov/34192429/
[101/221] ✓   2,338 chars │ https://pubmed.ncbi.nlm.nih.gov/32945884/
[102/221] ✓   2,718 chars │ https://pubmed.ncbi.nlm.nih.gov/35994207/
[103/221] ✓   2,884 chars │ https://pubmed.ncbi.nlm.nih.gov/34228377/
[104/221] ✓   2,423 chars │ https://pubmed.ncbi.nlm.nih.gov/32511847/
[105/221] ✓   4,212 chars │ https://pubmed.ncbi.nlm.nih.gov/33320097/
[106/221] ✓     196 chars │ https://pubmed.ncbi.nlm.nih.gov/8604028/
[107/221] ✓   3,620 chars │ https://pubmed.ncbi.nlm.nih.gov/25582427/
[108/221] ✓   1,298 chars │ https://pubmed.ncbi.nlm.nih.gov/38044623/
[109/221] ✓   3,358 chars │ https://pubmed.ncbi.nlm.nih.gov/28249596/
[110/221] ✓   3,875 chars │ https://pubmed.ncbi.nlm.nih.gov/12435255/
[111/221] ✓     564 chars │ https://pubmed.ncbi.nlm.nih.gov/28899075/
[112/221] ✓   2,010 chars │ https://pubmed.ncbi.nlm.nih.gov/19386036/
[113/221] ✓   1,822 chars │ https://pubmed.ncbi.nlm.nih.gov/19884777/
[114/221] ✓     799 chars │ https://pubmed.ncbi.nlm.nih.gov/35061006/
[115/221] ✓   6,842 chars │ https://pubmed.ncbi.nlm.nih.gov/33284946/
[116/221] ✓   1,754 chars │ https://pubmed.ncbi.nlm.nih.gov/32026975/
[117/221] ✓   2,143 chars │ https://pubmed.ncbi.nlm.nih.gov/39720530/
[118/221] ✓   2,696 chars │ https://pubmed.ncbi.nlm.nih.gov/31014089/
[119/221] ✓     796 chars │ https://pubmed.ncbi.nlm.nih.gov/16037222/
[120/221] ✓   1,949 chars │ https://pubmed.ncbi.nlm.nih.gov/16549665/
[121/221] ✓   3,246 chars │ https://pubmed.ncbi.nlm.nih.gov/20439601/
[122/221] ✓   2,379 chars │ https://pubmed.ncbi.nlm.nih.gov/15571958/
[123/221] ✓   1,656 chars │ https://pubmed.ncbi.nlm.nih.gov/28583955/
[124/221] ✓   3,372 chars │ https://pubmed.ncbi.nlm.nih.gov/28493664/
[125/221] ✓   2,514 chars │ https://pubmed.ncbi.nlm.nih.gov/28777724/
[126/221] ✓   1,882 chars │ https://pubmed.ncbi.nlm.nih.gov/30629181/
[127/221] ✓   1,328 chars │ https://pubmed.ncbi.nlm.nih.gov/30699025/
[128/221] ✓   2,682 chars │ https://pubmed.ncbi.nlm.nih.gov/31248415/
[129/221] ✓   2,534 chars │ https://pubmed.ncbi.nlm.nih.gov/25789077/
[130/221] ✓   3,135 chars │ https://pubmed.ncbi.nlm.nih.gov/32146931/
[131/221] ✓   2,313 chars │ https://pubmed.ncbi.nlm.nih.gov/28936010/
[132/221] ✓   1,261 chars │ https://pubmed.ncbi.nlm.nih.gov/19371159/
[133/221] ✓  54,707 chars │ https://oheace.cdph.ca.gov/tech-resources/slo-health-equity-plan.pdf
[134/221] ✓ 560,670 chars │ https://dhss.delaware.gov/wp-content/uploads/sites/10/dph/pdf/heg2nded.pdf
[135/221] ✓  61,557 chars │ https://www.ncdhhs.gov/heia-implementation-guide/open
[136/221] ✓  52,203 chars │ https://schs.dph.ncdhhs.gov/SCHS/pdf/MinorityHealthReport_Web_2018.pdf
[137/221] ✓ 149,907 chars │ https://www.sandiegocounty.gov/content/dam/sdc/hhsa/programs/phs/health-equity/P...
[138/221] ✓ 138,423 chars │ https://portal.ct.gov/-/media/departments-and-agencies/dph/dph/hems/health_equit...
[139/221] ✓  60,090 chars │ https://www.nyc.gov/assets/doh/downloads/pdf/cmo/community-health-workers-health...
[140/221] ✓  71,114 chars │ https://hcpf.colorado.gov/sites/hcpf/files/RAE%204%20Health%20Equity%20Plan%20FY...
[141/221] ✗      85 chars │ https://www.clatsopcounty.gov/media/50016
[142/221] ✓ 121,239 chars │ https://www.pa.gov/content/dam/copapwp-pagov/en/health/documents/topics/document...
[143/221] ✓  99,677 chars │ https://www.hca.wa.gov/assets/program/state-of-health-equity-measurement-white-p...
[144/221] ✓  18,124 chars │ https://www.healthvermont.gov/sites/default/files/documents/pdf/2%20Health%20Equ...
[145/221] ✓  69,556 chars │ https://www.azdhs.gov/documents/prevention/chronic-disease/health-disparities/pu...
[146/221] ✓  17,370 chars │ https://doh.wa.gov/sites/default/files/legacy/Documents/8300/140-044-HERtool-en-...
[147/221] ✓ 196,640 chars │ https://www.dhs.nv.gov/siteassets/content/programs/nomhe/mh/Health_Equity_Action...
[148/221] ✓  44,373 chars │ https://health.maryland.gov/mche/Documents/MCHE%20Annual%20Report%20-%20Final.pd...
[149/221] ✓ 216,426 chars │ https://health.maryland.gov/pha/Documents/PHAB%20documents/2026%20State%20Health...
[150/221] ✓   7,717 chars │ https://www.health.mn.gov/communities/practice/resources/publications/docs/1811a...
[151/221] ✓  14,181 chars │ https://www.health.mn.gov/communities/equity/reports/aheexecutivesummary.pdf
[152/221] ✓  45,910 chars │ https://assets.ramseycountymn.gov/files/migrated-files/HEDA_10.12.17.pdf
[153/221] ✗     351 chars │ https://www.cdph.ca.gov/Programs/OHE/CDPH%20Document%20Library/Accessible-CDPH_O...
[154/221] ✓ 281,784 chars │ https://malegislature.gov/Reports/11522/Final%20Health%20Equity%20Task%20Force%2...
[155/221] ✗     306 chars │ https://sharedsystems.dhsoha.state.or.us/DHSForms/Served/le-683051.pdf
[156/221] ✓ 171,754 chars │ https://dph.illinois.gov/content/dam/soi/en/web/idph/publications/idph/topics-an...
[157/221] ✓ 198,956 chars │ https://www.michigan.gov/-/media/Project/Websites/mdhhs/Folder1/Folder55/Michiga...
[158/221] ✓  32,002 chars │ https://www.nj.gov/health/about/documents/njdoh-strategic-plan.pdf
[159/221] ✓ 113,767 chars │ http://publichealth.lacounty.gov/CenterForHealthEquity/PDF/CHEActionPlanFinalDra...
[160/221] ✓ 191,412 chars │ https://aqua.kingcounty.gov/dnrp/library/dnrp-directors-office/equity-social-jus...
[161/221] ✓  46,092 chars │ https://www.dhs.wisconsin.gov/publications/p03091-2022-02.pdf
[162/221] ✓  31,634 chars │ https://files.kff.org/attachment/health-policy-101-race-inequality-and-health.pd...
[163/221] ✓  38,985 chars │ https://files.kff.org/attachment/Issue-Brief-Disparities-in-Health-and-Health-Ca...
[164/221] ✓  46,229 chars │ https://files.kff.org/attachment/issue-brief-beyond-health-care
[165/221] ✓  65,641 chars │ https://files.kff.org/attachment/Report-Racial-and-Ethnic-Health-Inequities-and-...
[166/221] ✓  33,496 chars │ https://www.kff.org/wp-content/uploads/2014/06/8606-discussion-of-health-care-an...
[167/221] ✓  46,280 chars │ https://www.commonwealthfund.org/publications/fund-reports/2024/apr/advancing-ra...
[168/221] ✓  43,584 chars │ https://www.commonwealthfund.org/publications/scorecard/2021/nov/achieving-racia...
[169/221] ✓   4,950 chars │ https://www.commonwealthfund.org/sites/default/files/2020-11/CMWF_DSR_Task_Force...
[170/221] ✓ 132,869 chars │ https://www.commonwealthfund.org/sites/default/files/2024-09/Blumenthal_mirror_m...
[171/221] ✓  25,470 chars │ https://www.urban.org/sites/default/files/2023-08/Unequal%20Treatment%20at%2020-...
[172/221] ✓ 131,933 chars │ https://www.urban.org/sites/default/files/2023-12/Envisioning_a_New_Health_Syste...
[173/221] ✓  90,390 chars │ https://www.urban.org/sites/default/files/2023-10/Using%20Race%20and%20Ethnicity...
[174/221] ✓  38,876 chars │ https://www.urban.org/sites/default/files/2024-05/Guide_to_Equity_in_Behavioral_...
[175/221] ✓ 116,306 chars │ https://www.urban.org/sites/default/files/2022-07/Collection%20of%20Race%20and%2...
[176/221] ✓  26,215 chars │ https://www.urban.org/sites/default/files/2024-01/Guide%20to%20Equity%20for%20th...
[177/221] ✓  26,945 chars │ https://www.urban.org/sites/default/files/2024-01/Guide%20to%20Equity%20in%20Med...
[178/221] ✓ 202,860 chars │ https://familiesusa.org/wp-content/uploads/2018/06/FamiliesUSA_Policy-Options_Re...
[179/221] ✓  56,173 chars │ https://familiesusa.org/wp-content/uploads/2019/10/National-Priorities_Report.pd...
[180/221] ✓  33,456 chars │ https://familiesusa.org/wp-content/uploads/2019/03/HEV_Data-Stratification_-Issu...
[181/221] ✓  26,565 chars │ https://familiesusa.org/wp-content/uploads/2023/04/HE-Policy-Priorities.pdf
[182/221] ✓  73,934 chars │ https://familiesusa.org/wp-content/uploads/2019/11/HEV_PCORI-CHW-Report_11-04-19...
[183/221] ✓  24,036 chars │ https://familiesusa.org/wp-content/uploads/2017/12/Health-Equity-and-Value-Call-...
[184/221] ✓  46,315 chars │ https://familiesusa.org/wp-content/uploads/2020/12/HE-12_Making-Progress-toward-...
[185/221] ✓   7,310 chars │ https://www.rwjf.org/en/insights/our-research/2017/05/what-is-health-equity-.htm...
[186/221] ✓ 143,644 chars │ https://www.rwjf.org/content/dam/files/rwjf-web-files/Research/2015/From_Vision_...
[187/221] ✓   7,724 chars │ https://nap.nationalacademies.org/catalog/24624/communities-in-action-pathways-t...
[188/221] ✓   8,237 chars │ https://www.rwjf.org/en/insights/our-research/2021/10/charting-a-course-for-an-e...
[189/221] ✓   3,728 chars │ https://www.aha.org/ahahret-guides/2015-01-29-equity-care-toolkit-eliminating-he...
[190/221] ✓   2,980 chars │ https://www.ihi.org/library/white-papers/achieving-health-equity-guide-health-ca...
[191/221] ✓      36 chars │ https://nul.org/state-of-black-america
[192/221] ✓     160 chars │ https://www.brookings.edu/articles/time-for-justice-tackling-race-inequalities-i...
[193/221] ✓  39,110 chars │ https://www.statnews.com/2021/09/23/health-equity-tourists-white-scholars-coloni...
[194/221] ✓  16,957 chars │ https://kffhealthnews.org/news/article/black-american-south-carolina-health-disp...
[195/221] ✓   6,685 chars │ https://kffhealthnews.org/news/article/black-americans-mortality-gap-racial-disp...
[196/221] ✓  11,501 chars │ https://kffhealthnews.org/news/article/racism-derails-black-mens-health-even-as-...
[197/221] ✓   2,908 chars │ https://kffhealthnews.org/news/article/racism-violence-black-american-health-pod...
[198/221] ✓   9,029 chars │ https://kffhealthnews.org/news/article/growing-disparity-life-expectancy-racial-...
[199/221] ✓  30,960 chars │ https://www.brookings.edu/articles/achieving-an-equitable-national-health-system...
[200/221] ✓  41,887 chars │ https://www.brookings.edu/articles/re-balancing-medical-and-social-spending-to-p...
[201/221] ✓     167 chars │ https://www.brookings.edu/articles/promote-health-equity-by-taxing-sugary-drinks...
[202/221] ✓   8,216 chars │ https://www.statnews.com/2021/11/19/health-plans-insurers-addressing-racial-ineq...
[203/221] ✓   7,318 chars │ https://www.statnews.com/2021/12/03/in-defense-of-not-treating-everyone-the-same...
[204/221] ✓  11,528 chars │ https://kffhealthnews.org/news/article/black-doctor-shortage-mississippi-diversi...
[205/221] ✗     106 chars │ https://healthaffairs.org/do/10.1377/hblog20170522.060211/full
[206/221] ✗     104 chars │ https://www.healthaffairs.org/doi/10.1377/hlthaff.2024.00036
[207/221] ✓  25,503 chars │ https://www.brookings.edu/articles/5-building-blocks-to-help-achieve-greater-hea...
[208/221] ✓  11,227 chars │ https://www.brookings.edu/articles/using-digital-health-to-improve-health-outcom...
[209/221] ✓   7,957 chars │ https://www.statnews.com/2024/08/05/cost-effectiveness-analyses-that-perpetuate-...
[210/221] ✓  22,792 chars │ https://www.statnews.com/2022/02/24/little-progress-health-equity-these-leaders-...
[211/221] ✓   8,986 chars │ https://www.statnews.com/2024/06/26/national-academies-report-ending-unequal-tre...
[212/221] ✗     162 chars │ https://www.healthaffairs.org/content/forefront/health-equity-should-key-value-v...
[213/221] ✗     111 chars │ https://www.healthaffairs.org/do/10.1377/forefront.20240603.385559/
[214/221] ✗      94 chars │ https://www.nejm.org/doi/full/10.1056/NEJMp2215539
[215/221] ✗     141 chars │ https://www.ajmc.com/view/navigating-health-equity-in-2024-the-evolution-of-acco...
[216/221] ✓  13,699 chars │ https://www.brookings.edu/articles/dobbs-another-frontline-for-health-equity/
[217/221] ✓   8,409 chars │ https://www.statnews.com/2024/04/03/dei-in-medicine-under-attack-and-health-care...
[218/221] ✓     122 chars │ https://www.statnews.com/2024/08/15/hhs-climate-change-climate-washing-health-ca...
[219/221] ✓   5,843 chars │ https://kffhealthnews.org/news/article/health-care-quality-race-appearance-kff-s...

## Step 3 – Preview Results

In [ ]:
df = pd.DataFrame(records)
df["text_length"] = df["scraped_text"].str.len()
df["is_error"] = df["scraped_text"].str.startswith("ERROR")

summary = (
    df.groupby("category")
    .agg(
        entries=("url", "count"),
        success=("is_error", lambda x: (~x).sum()),
        failed=("is_error", "sum"),
        avg_chars=("text_length", lambda x: x[~df.loc[x.index, "is_error"]].mean()),
    )
    .round(0)
)

summary

,entries,success,failed,avg_chars
category,,,,
Academic article abstracts,100,92,8,4455.0
Distribution / access / resource framing,8,6,2,16679.0
Federal policy / government health policy documents,32,27,5,71030.0
Mixed / ambiguous framing,6,6,0,15091.0
NGO / nonprofit health reports/documents,30,30,0,51227.0
Policy implementation / measurement / systems framing,9,5,4,15293.0
State or local health department reports/documents,29,26,3,116756.0
Structural / justice framing,7,7,0,12336.0

In [10]:
# Show any failures for manual inspection
failures = df[df["is_error"]][["category", "title", "url", "scraped_text"]]
if len(failures) > 0:
    print(f"{len(failures)} failed URLs:\n")
    for _, row in failures.iterrows():
        print(f"  • {row['title']}")
        print(f"    {row['url']}")
        print(f"    {row['scraped_text'][:100]}\n")
else:
    print("All URLs scraped successfully!")

22 failed URLs:

  • Focusing on Health Equity
    https://stacks.cdc.gov/view/cdc/126226/cdc_126226_DS1.pdf
    ERROR: 403 Client Error: Forbidden for url: https://stacks.cdc.gov/view/cdc/126226/cdc_126226_DS1.pd

  • Promoting Health Equity: A Resource to Help Communities Address Social Determinants of Health
    https://stacks.cdc.gov/view/cdc/11130/cdc_11130_DS1.pdf
    ERROR: 403 Client Error: Forbidden for url: https://stacks.cdc.gov/view/cdc/11130/cdc_11130_DS1.pdf

  • Health Equity Report 2019–2020
    https://www.hrsa.gov/sites/default/files/hrsa/about/news/hrsa-health-equity-report.pdf
    ERROR: 403 Client Error: Forbidden for url: https://www.hrsa.gov/sites/default/files/hrsa/about/news

  • Healthy People 2030: Health Equity in Healthy People 2030
    https://health.gov/healthypeople
    ERROR: 404 Client Error: Not Found for url: https://health.gov/healthypeople

  • SAMHSA Behavioral Health Equity Framework
    https://www.samhsa.gov/behavioral-health-equity
    ERROR: 404 Client Error: Not Found for url: https://www.samhsa.gov/behavioral-health-equity

  • Medicaid can and should play an active role in advancing health equity
    https://onlinelibrary.wiley.com/doi/10.1111/1475-6773.14069
    ERROR: 403 Client Error: Forbidden for url: https://onlinelibrary.wiley.com/doi/10.1111/1475-6773.14

  • Health Equity in Public Health: Clarifying our Commitment
    https://academic.oup.com/phe/article-abstract/8/2/173/2362531
    ERROR: 403 Client Error: Forbidden for url: https://academic.oup.com/phe/article-abstract/8/2/173/23

  • (Re)Engaging the Normative in Public Health Discourse and Practice? The Case of Health Equity
    https://academic.oup.com/phe/article-abstract/13/3/247/5874652
    ERROR: 403 Client Error: Forbidden for url: https://academic.oup.com/phe/article-abstract/13/3/247/5

  • Food Sovereignty, Food Security and Health Equity: A Meta-Narrative Mapping Exercise
    https://academic.oup.com/heapol/article-abstract/30/8/1078/555203
    ERROR: 403 Client Error: Forbidden for url: https://academic.oup.com/heapol/article-abstract/30/8/10

  • A Health Equity Framework for the US Preventive Services Task Force
    https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2815866
    ERROR: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jamanetworkopen/fullart

  • A Road Map for Population Health and Health Equity Research
    https://jamanetwork.com/journals/jamapediatrics/article-abstract/2819321
    ERROR: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jamapediatrics/article-

  • The US Health Equity Crisis — An Economic Case for a Moral Imperative?
    https://jamanetwork.com/journals/jama/article-abstract/2804847
    ERROR: 403 Client Error: Forbidden for url: https://jamanetwork.com/journals/jama/article-abstract/2

  • Advancing a Health Equity Agenda Across Multiple Policy Domains: a Qualitative Policy Analysis
    https://bmjopen.bmj.com/content/10/11/e040180
    ERROR: 403 Client Error: Forbidden for url: https://bmjopen.bmj.com/content/10/11/e040180

  • Health Equity Plan
    https://www.clatsopcounty.gov/media/50016
    ERROR: 403 Client Error: Forbidden for url: https://www.clatsopcounty.gov/media/50016

  • Portrait of Promise: The California Statewide Plan to Promote Health and Mental Health Equity
    https://www.cdph.ca.gov/Programs/OHE/CDPH%20Document%20Library/Accessible-CDPH_OHE_Disparity_Report_Race_Equity.pdf
    ERROR: HTTPSConnectionPool(host='www.cdph.ca.gov', port=443): Max retries exceeded with url: /Progra

  • Oregon Health Equity Review
    https://sharedsystems.dhsoha.state.or.us/DHSForms/Served/le-683051.pdf
    ERROR: HTTPSConnectionPool(host='sharedsystems.dhsoha.state.or.us', port=443): Max retries exceeded

  • Health Insurance Benefits Should Be Equitable, Not Necessarily Equal
    https://healthaffairs.org/do/10.1377/hblog20170522.060211/full
    ERROR: 403 Client Error: Forbidden for url: https://healthaffairs.org/do/10.1377/hblog20170522.06021

  • Reimagining Rural Health Equity
    https://www.healthaffairs.org/doi/10.1377/hlthaff.2024.00036
    ERROR: 403 Client Error: Forbidden for url: https://www.healthaffairs.org/doi/10.1377/hlthaff.2024.0

  • Health Equity Should Be a Key Value in Value-Based Payment and Delivery Reform
    https://www.healthaffairs.org/content/forefront/health-equity-should-key-value-value-based-payment-and-delivery-reform
    ERROR: 403 Client Error: Forbidden for url: https://www.healthaffairs.org/content/forefront/health-e

  • Advancing Health Equity Through Value-Based Care: CMS Innovation Center Update
    https://www.healthaffairs.org/do/10.1377/forefront.20240603.385559/
    ERROR: 403 Client Error: Forbidden for url: https://www.healthaffairs.org/do/10.1377/forefront.20240

  • Aligning Quality Measures across CMS: The Universal Foundation
    https://www.nejm.org/doi/full/10.1056/NEJMp2215539
    ERROR: 403 Client Error: Forbidden for url: https://www.nejm.org/doi/full/10.1056/NEJMp2215539

  • Navigating Health Equity in 2024: The Evolution of Accountability, Part 1
    https://www.ajmc.com/view/navigating-health-equity-in-2024-the-evolution-of-accountability-part-1
    ERROR: 403 Client Error: Forbidden for url: https://www.ajmc.com/view/navigating-health-equity-in-20

## Step 4 – Write to Excel

In [12]:
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE


def sanitize_excel_value(value):
    if not isinstance(value, str):
        return value
    return ILLEGAL_CHARACTERS_RE.sub("", value)


def write_excel(records: list[dict], output_path: str):
    wb = Workbook()
    ws = wb.active
    ws.title = "Corpus"

    columns = [
        ("Entry", 8),
        ("Category", 35),
        ("Title", 50),
        ("Source", 20),
        ("URL", 60),
        ("Description", 50),
        ("Scraped_Text", 80),
    ]

    header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill("solid", fgColor="2F5496")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin_border = Border(bottom=Side(style="thin", color="B0B0B0"))
    cell_font = Font(name="Arial", size=10)
    wrap_align = Alignment(vertical="top", wrap_text=True)

    for col_idx, (name, width) in enumerate(columns, 1):
        cell = ws.cell(row=1, column=col_idx, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        ws.column_dimensions[cell.column_letter].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:G{len(records) + 1}"

    for row_idx, rec in enumerate(records, 2):
        values = [
            row_idx - 1,
            rec["category"],
            rec["title"],
            rec["source_label"],
            rec["url"],
            rec["description"],
            rec["scraped_text"],
        ]
        for col_idx, val in enumerate(values, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=sanitize_excel_value(val))
            cell.font = cell_font
            cell.alignment = wrap_align
            cell.border = thin_border

    wb.save(output_path)
    print(f"Wrote {len(records)} rows -> {output_path}")


write_excel(records, OUTPUT_XLSX)

Wrote 221 rows -> equity_corpus_scraped.xlsx

## Step 5 – Extract "Equity" Contexts

Extract ±1 sentence around every occurrence of "equity".

In [9]:
import re


SENTENCE_BOUNDARY_RE = re.compile(r"(?<=[.!?])\s+")


def split_sentences(text: str) -> list[str]:
    text = re.sub(r"\s+", " ", text).strip()
    if not text or text.startswith("ERROR"):
        return []
    return [
        sentence.strip()
        for sentence in SENTENCE_BOUNDARY_RE.split(text)
        if sentence.strip()
    ]


def extract_equity_contexts(text: str, window: int = 1) -> list[str]:
    """Return +/-window sentences around every sentence containing 'equity'."""
    sentences = split_sentences(text)
    contexts = []
    for i, sent in enumerate(sentences):
        if re.search(r"\bequity\b", sent, re.IGNORECASE):
            start = max(0, i - window)
            end = min(len(sentences), i + window + 1)
            context = " ".join(sentences[start:end])
            contexts.append(context)
    return contexts


context_rows = []
for rec in records:
    contexts = extract_equity_contexts(rec["scraped_text"])
    for ctx in contexts:
        context_rows.append(
            {
                "category": rec["category"],
                "title": rec["title"],
                "source_label": rec["source_label"],
                "url": rec["url"],
                "equity_context": ctx,
            }
        )

df_contexts = pd.DataFrame(context_rows)
print(f"Extracted {len(df_contexts)} equity contexts from {len(records)} documents")
df_contexts.head(10)

Extracted 6109 equity contexts from 221 documents

,category,title,source_label,url,equity_context
0,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,C O N T R A C T O R P R O J E C T R E P O R T ...
1,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,"ASPE wrote two Reports to Congress, making rec..."
2,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,This included the recommendations that the Cen...
3,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,"Moreover, in the ASPE commissioned report, Sys..."
4,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,"In response to this challenge, ASPE asked the ..."
5,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,RAND identified 10 existing approaches to heal...
6,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,"Based on input from RAND, ASPE, and the TEP, i..."
7,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,The purpose of including health equity measure...
8,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,It could also encourage providers to improve h...
9,Federal policy / government health policy docu...,Developing Health Equity Measures,ASPE / HHS,https://aspe.hhs.gov/sites/default/files/priva...,"Washington, DC: The National Academies Press. ..."

In [ ]:
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE


def sanitize_dataframe_for_excel(df: pd.DataFrame) -> pd.DataFrame:
    cleaned = df.copy()
    object_columns = cleaned.select_dtypes(include=["object", "string"]).columns
    for column in object_columns:
        cleaned[column] = cleaned[column].map(
            lambda value: (
                ILLEGAL_CHARACTERS_RE.sub("", value)
                if isinstance(value, str)
                else value
            )
        )
    return cleaned


OUTPUT_CONTEXT_CSV.parent.mkdir(parents=True, exist_ok=True)
df_contexts_excel = sanitize_dataframe_for_excel(df_contexts)
df_contexts_excel.to_csv(OUTPUT_CONTEXT_CSV, index=False)
print(f"Saved -> {OUTPUT_CONTEXT_CSV}")

Saved -> equity_contexts.xlsx